In [29]:
%load_ext rpy2.ipython
import pandas as pd

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython

### 0. Parameters
Set the working directory:

In [30]:
root = "/data/project/sleep_ENIGMA_glymphatic/enigma-sd"
%cd $root

/data/project/sleep_ENIGMA_glymphatic/enigma-sd

Load the data:

In [31]:
master_data = pd.read_csv("outputs/master_dataframe.csv")

Load the required R packages:

In [32]:
%%R
packages = c('dplyr','tidyverse','remotes','neuroCombat')
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
require(packages)
lapply(packages, require, character.only = TRUE)

* installing *source* package ‘ragg’ ...
** package ‘ragg’ successfully unpacked and MD5 sums checked
** using staged installation
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libtiff-4', required by 'virtual:world', not found
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libtiff-4', required by 'virtual:world', not found
ERROR: configuration failed for package ‘ragg’
* removing ‘/home/jd.elberse/.R/library/ragg’

Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype -lpng16 -ltiff -lz -ljpeg -lbz2
-----------------------------[ ANTICONF ]-------------------------------
Configuration failed to find one of freetype2 libpng libtiff-4 libjpeg. Try installing:
 * deb: libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev (Debian, Ubuntu, etc)
 * rpm: freetype-devel libpng-devel libtiff-devel libjpeg-devel (Fedora, CentOS, RHEL)
If freetype2 libpng libtiff-4 libjpeg is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a freetype2 libpng libtiff-4 libjpeg.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: ft2build.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
[[1]]
[1] TRUE

[[2]]
[1] FALSE

[[3]]
[1] TRUE

[[4]]
[1] TRUE

ERROR: dependency ‘ragg’ is not available for package ‘tidyverse’
* removing ‘/home/jd.elberse/.R/library/tidyverse’

Installing package into ‘/home/jd.elberse/.R/library’
(as ‘lib’ is unspecified)
also installing the dependency ‘ragg’

trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/ragg_1.4.0.tar.gz'
Content type 'application/octet-stream' length 430819 bytes (420 KB)
==================================================
downloaded 420 KB

trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/tidyverse_2.0.0.tar.gz'
Content type 'application/octet-stream' length 704618 bytes (688 KB)
==================================================
downloaded 688 KB


The downloaded source packages are in
	‘/tmp/RtmpVXGe9s/downloaded_packages’
Loading required package: packages
Loading required package: tidyverse
In addition: Warning messages:
1: In install.packages(new.packages) :
  installation of package ‘ragg’ had non-zero exit status
2: In install.packages(new.packages) :
  installation of package ‘tidyverse’ had non-zero exit status
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘packages’
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘tidyverse’

### 1. Reformat Data
Load the master dataframe:

In [33]:
df = pd.read_csv("outputs/master_dataframe.csv")
df

,participant_id,site,group,age,sex,kss_score_baseline,kss_score_sd,chronotype,pvsvf_baseline,pvsvf_sd,cpvf_baseline,mfwi_baseline,rfwi_baseline,alps_baseline,cpvf_sd,mfwi_sd,rfwi_sd,alps_sd,dataset,protocol
0,sub-BRUX001,Bruxelles,4.0,19.000000,F,5.000000,7.000000,1.0,0.000848,0.001058,0.000419,0.208510,0.991973,1.217614,0.000380,0.207886,0.991811,1.215502,bruxelles-bids,SD
1,sub-BRUX003,Bruxelles,4.0,21.000000,F,3.000000,9.000000,1.0,0.001964,0.001926,0.000296,0.211102,0.991583,1.242567,0.000285,0.211231,0.991699,1.237313,bruxelles-bids,SD
2,sub-BRUX004,Bruxelles,4.0,19.000000,F,1.000000,6.000000,3.0,0.001030,0.001254,0.000265,0.209733,0.988161,1.095042,0.000214,0.209822,0.988203,1.055947,bruxelles-bids,SD
3,sub-BRUX006,Bruxelles,4.0,29.000000,F,2.000000,5.000000,3.0,0.000446,0.000448,0.000233,0.216413,0.989975,1.098525,0.000273,0.216092,0.989983,1.108122,bruxelles-bids,SD
4,sub-BRUX007,Bruxelles,4.0,20.000000,F,1.000000,6.000000,3.0,0.000692,0.000669,0.000243,0.205153,0.989306,1.347277,0.000249,0.205345,0.989475,1.348133,bruxelles-bids,SD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,sub-ZURI137,Zurich,4.0,23.052704,M,4.142857,7.571429,3.0,0.000922,0.000464,0.000397,NaN,NaN,NaN,0.000364,NaN,NaN,NaN,zurich-bids,SD
429,sub-ZURI138,Zurich,4.0,26.762491,M,2.857143,4.142857,1.0,0.000560,0.000510,0.000267,NaN,NaN,NaN,0.000302,NaN,NaN,NaN,zurich-bids,SD
430,sub-ZURI140,Zurich,4.0,25.752225,M,3.285714,6.285714,3.0,0.001232,0.001149,0.000377,NaN,NaN,NaN,0.000401,NaN,NaN,NaN,zurich-bids,SD
431,sub-ZURI141,Zurich,4.0,21.815195,M,2.857143,4.666667,3.0,0.000518,0.000438,0.000345,NaN,NaN,NaN,0.000328,NaN,NaN,NaN,zurich-bids,SD
432,sub-ZURI142,Zurich,4.0,25.930185,M,3.142857,5.714286,3.0,0.000701,0.000702,0.000209,NaN,NaN,NaN,0.000232,NaN,NaN,NaN,zurich-bids,SD

COMBAT prefers that our factors are one-hot encoded. We do the following:
* `sex` becomes `sex_male`, with TRUE = M and FALSE = F
* `chronotype` is split into `chrono_morning` (chronotype = 1), `chrono_evening` (chronotype = 2), with chronotype = 3 serving as the intercept.
* `protocol` becomes `total_deprivation`, with TRUE = SD protocol and FALSE = SR protocol.

In [34]:
# SEX
df["sex_male"] = df.sex == "M"

# CHRONO
df["chrono_morning"] = df.chronotype == 1
df["chrono_evening"] = df.chronotype == 2

# PROTOCOL
df["total_deprivation"] = df.protocol == "SD"

df

,participant_id,site,group,age,sex,kss_score_baseline,kss_score_sd,chronotype,pvsvf_baseline,pvsvf_sd,...,cpvf_sd,mfwi_sd,rfwi_sd,alps_sd,dataset,protocol,sex_male,chrono_morning,chrono_evening,total_deprivation
0,sub-BRUX001,Bruxelles,4.0,19.000000,F,5.000000,7.000000,1.0,0.000848,0.001058,...,0.000380,0.207886,0.991811,1.215502,bruxelles-bids,SD,False,True,False,True
1,sub-BRUX003,Bruxelles,4.0,21.000000,F,3.000000,9.000000,1.0,0.001964,0.001926,...,0.000285,0.211231,0.991699,1.237313,bruxelles-bids,SD,False,True,False,True
2,sub-BRUX004,Bruxelles,4.0,19.000000,F,1.000000,6.000000,3.0,0.001030,0.001254,...,0.000214,0.209822,0.988203,1.055947,bruxelles-bids,SD,False,False,False,True
3,sub-BRUX006,Bruxelles,4.0,29.000000,F,2.000000,5.000000,3.0,0.000446,0.000448,...,0.000273,0.216092,0.989983,1.108122,bruxelles-bids,SD,False,False,False,True
4,sub-BRUX007,Bruxelles,4.0,20.000000,F,1.000000,6.000000,3.0,0.000692,0.000669,...,0.000249,0.205345,0.989475,1.348133,bruxelles-bids,SD,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,sub-ZURI137,Zurich,4.0,23.052704,M,4.142857,7.571429,3.0,0.000922,0.000464,...,0.000364,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
429,sub-ZURI138,Zurich,4.0,26.762491,M,2.857143,4.142857,1.0,0.000560,0.000510,...,0.000302,NaN,NaN,NaN,zurich-bids,SD,True,True,False,True
430,sub-ZURI140,Zurich,4.0,25.752225,M,3.285714,6.285714,3.0,0.001232,0.001149,...,0.000401,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
431,sub-ZURI141,Zurich,4.0,21.815195,M,2.857143,4.666667,3.0,0.000518,0.000438,...,0.000328,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
432,sub-ZURI142,Zurich,4.0,25.930185,M,3.142857,5.714286,3.0,0.000701,0.000702,...,0.000232,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True

We create individual dataframes from the different variable types:
* `Batch Feature`: the source of the variation we are trying to remove
* `Biological Features`: the features whose variation needs to be maintained
* `Anatomical/Diffusion Features`: the MRI-derived features that need to be corrected for the batch effect

Anatomical and diffusion covariates are harmonised separately because not all sites have DWI data.

In [35]:
## ANAT
anat_subs = df["participant_id"]
anat_batch = df["site"]
anat_bio = df[["age","sex_male","kss_score_baseline","kss_score_sd","chrono_morning","chrono_evening"]]
anat_feat = df[["pvsvf_baseline","pvsvf_sd","cpvf_baseline","cpvf_sd"]]

## DWI
dwi_df = df.dropna(subset="alps_baseline")
dwi_subs = dwi_df["participant_id"]
dwi_batch = dwi_df["site"]
dwi_bio = dwi_df[["age","sex_male","kss_score_baseline","kss_score_sd","chrono_morning","chrono_evening"]]
dwi_feat = dwi_df[["mfwi_baseline","mfwi_sd","alps_baseline","alps_sd"]]

The model matrix cannot handle missing values, so we must check our biological features for NAs and impute missing values.

In [36]:
for col in ["kss_score_baseline", "kss_score_sd"]:
    anat_bio.loc[:,col] = anat_bio[col].fillna(anat_bio[col].median())
    dwi_bio.loc[:,col] = dwi_bio[col].fillna(dwi_bio[col].median())

/tmp/ipykernel_10305/2360608552.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anat_bio.loc[:,col] = anat_bio[col].fillna(anat_bio[col].median())
/tmp/ipykernel_10305/2360608552.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dwi_bio.loc[:,col] = dwi_bio[col].fillna(dwi_bio[col].median())

Save a copy of the dataset pre-harmonization:

In [37]:
df.to_csv("outputs/master_dataframe_v2.csv")

### 2. Harmonization
Create batch vectors:

In [38]:
%%R -i anat_batch,dwi_batch
anat.batch <- as.numeric(as.factor(anat_batch))
dwi.batch <- as.numeric(as.factor(dwi_batch))

Create the model matrices:

In [39]:
%%R -i anat_bio,dwi_bio
anat.mod <- model.matrix(~age+sex_male+kss_score_baseline+kss_score_sd+chrono_morning+chrono_evening, data=anat_bio)
dwi.mod <- model.matrix(~age+sex_male+kss_score_baseline+kss_score_sd+chrono_morning+chrono_evening, data=dwi_bio)

Check that each of the variables is the right size:

In [40]:
%%R -i anat_feat
cat("nrow(anat.mod):", nrow(anat.mod), "\n")
cat("length(anat.batch):", length(anat.batch), "\n")
cat("ncol(t(anat_feat)):", ncol(t(anat_feat)), "\n")

nrow(anat.mod): 433
length(anat.batch): 433
ncol(t(anat_feat)): 433

Run harmonization for the anatomical features:

In [41]:
%%R -i anat_feat,anat_subs
rownames(anat_feat) <- anat_subs
anat.harmonized <- neuroCombat(dat=t(anat_feat), batch=anat.batch, mod=anat.mod)
anat.harmonized

[neuroCombat] Performing ComBat with empirical Bayes
[neuroCombat] Found 9 batches
[neuroCombat] Adjusting for  6  covariate(s) or covariate level(s)
[neuroCombat] Standardizing Data across features
[neuroCombat] Fitting L/S model and finding priors
[neuroCombat] Finding parametric adjustments
[neuroCombat] Adjusting the Data
$dat.combat
                sub-BRUX001  sub-BRUX003  sub-BRUX004  sub-BRUX006  sub-BRUX007
pvsvf_baseline 0.0005548189 0.0017257608 0.0007549547 1.197572e-04 0.0003984379
pvsvf_sd       0.0007448507 0.0016702745 0.0009619281 7.437701e-05 0.0003376216
cpvf_baseline  0.0004278484 0.0003021893 0.0002703924 2.368492e-04 0.0002482943
cpvf_sd        0.0003971990 0.0002958002 0.0002228461 2.821560e-04 0.0002590633
                sub-BRUX008  sub-BRUX010  sub-BRUX012  sub-BRUX013  sub-BRUX014
pvsvf_baseline 0.0002688991 0.0005722442 0.0003665644 7.444265e-05 0.0002112949
pvsvf_sd       0.0002473847 0.0004991764 0.0002301892 3.120521e-05 0.0002042260
cpvf_baseline  0.0001306648 0.0001407570 0.0002071214 3.145801e-04 0.0003346345
cpvf_sd        0.0002018218 0.0001293300 0.0002021991 3.273188e-04 0.0003705176
                sub-BRUX015  sub-BRUX017  sub-BRUX018  sub-BRUX019  sub-BRUX020
pvsvf_baseline 0.0007531982 0.0002174118 1.183843e-04 0.0005616623 0.0003333402
pvsvf_sd       0.0006743846 0.0002387659 9.555809e-05 0.0005152148 0.0002979053
cpvf_baseline  0.0002682405 0.0002782830 2.014239e-04 0.0003071508 0.0002680759
cpvf_sd        0.0002842749 0.0002837420 1.331895e-04 0.0003313878 0.0003028983
                sub-BRUX021  sub-BRUX022  sub-BRUX023  sub-BRUX024  sub-BRUX025
pvsvf_baseline 0.0007191595 0.0031636196 0.0008417749 0.0006061953 0.0006211321
pvsvf_sd       0.0008127111 0.0030641888 0.0008076326 0.0006373458 0.0005952541
cpvf_baseline  0.0002927472 0.0004989358 0.0003302386 0.0003392589 0.0003678572
cpvf_sd        0.0003636569 0.0004174538 0.0002415718 0.0003683981 0.0003483081
                sub-BRUX026  sub-BRUX027  sub-BRUX029  sub-BRUX030  sub-BRUX070
pvsvf_baseline 0.0003793054 0.0006542832 1.555757e-04 0.0003516149 0.0017609015
pvsvf_sd       0.0003612896 0.0006142071 9.307179e-05 0.0002539693 0.0016028521
cpvf_baseline  0.0004528495 0.0005523617 3.115556e-04 0.0002120734 0.0003418567
cpvf_sd        0.0004678150 0.0003989885 3.089123e-04 0.0002064480 0.0003873905
               sub-JUPE118019 sub-JUPE118029 sub-JUPE118038 sub-JUPE118055
pvsvf_baseline   0.0007448190   0.0003666137   0.0001815413   0.0010449027
pvsvf_sd         0.0005724802   0.0002354862   0.0001118020   0.0009987133
cpvf_baseline    0.0002203526   0.0004906208   0.0002592649   0.0002714893
cpvf_sd          0.0002385888   0.0004064243   0.0003312580   0.0002557721
               sub-JUPE118056 sub-JUPE118068 sub-JUPE118107 sub-JUPE118151
pvsvf_baseline   0.0003026338   0.0019045825   0.0008819774   0.0009767438
pvsvf_sd         0.0003405310   0.0018416957   0.0009777448   0.0010701627
cpvf_baseline    0.0003321340   0.0002987787   0.0002056941   0.0003611187
cpvf_sd          0.0002931020   0.0002819134   0.0001873918   0.0002874002
               sub-JUPE118162 sub-JUPE118179 sub-JUPE118256 sub-JUPE118313
pvsvf_baseline   0.0003135566   0.0008247997   0.0002090711   0.0008410626
pvsvf_sd         0.0001925995   0.0008425981   0.0003430643   0.0010624151
cpvf_baseline    0.0001857257   0.0004281201   0.0004654973   0.0004289196
cpvf_sd          0.0001752407   0.0004718189   0.0004170633   0.0003442625
               sub-JUPE118345  sub-JUSL018  sub-JUSL067  sub-JUSL070
pvsvf_baseline   0.0003115848 0.0026869974 0.0006662434 1.326981e-04
pvsvf_sd         0.0003652641 0.0027151741 0.0006227008 7.288615e-05
cpvf_baseline    0.0003222782 0.0004404538 0.0004852090 3.135831e-04
cpvf_sd          0.0003034992 0.0004140442 0.0004636388 3.000859e-04
                sub-JUSL080  sub-JUSL083  sub-JUSL104  sub-JUSL156  sub-JUSL180
pvsvf_baseline 0.0007306961 0.0001977723 0.0005086954 0.0022610843 0.0012278811
pvsvf_sd       0.0006298788 0.0005989333 0.0007101051 0.0019086142 0.0013196067
cpvf_baseline  0.0003502119 0.0003076236 0.0001904640 0.0003123253 0.0003080233
cpvf_sd        0.0003195327 0.0003173603 0.0002139645 0.0002874798 0.0003199965
                sub-JUSL182  sub-JUSL183  sub-JUSL198  sub-JUSL204  sub-JUSL207
pvsvf_baseline 0.0003532343 0.0006901317 0.0006833026 0.0021706113 0.0007214164
pvsvf_sd       0.0003745200 0.0007161412 0.0006809989 0.0022900961 0.0008678580
cpvf_baseline  0.0001827423 0.0002372096 0.0002605032 0.0004263381 0.0001998958
cpvf_sd        0.0001854227 0.0002083848 0.0002734197 0.0005912333 0.0002065925
                sub-JUSL221  sub-JUSL256  sub-JUSL259 sub-JUSL261  sub-JUSL280
pvsvf_baseline 0.0038060637 0.0004417973 0.0011126838 0.001570365 0.0012548535
pvsvf_sd       0.0040502720 0.0004281572 0.0014531263 0.001730432 0.0010665353
cpvf_baseline  0.0004755991 0.0003227792 0.0006940678 0.000287717 0.0005936283
cpvf_sd        0.0003876604 0.0003062257 0.0006328817 0.000294937 0.0005124528
                sub-JUSL295  sub-JUSL321  sub-JUSL322  sub-JUSL326  sub-JUSL332
pvsvf_baseline 0.0008172707 0.0004823167 0.0005032929 0.0012473483 0.0002262464
pvsvf_sd       0.0008147677 0.0003371664 0.0005411154 0.0010971129 0.0002077017
cpvf_baseline  0.0004599704 0.0002166971 0.0004870159 0.0004256265 0.0003648946
cpvf_sd        0.0004754865 0.0002761978 0.0004813415 0.0004569085 0.0003784061
                sub-JUSL333  sub-JUSL353  sub-JUSL354  sub-JUSL391  sub-JUSL413
pvsvf_baseline 0.0012643181 0.0009801018 0.0012644690 0.0010151316 0.0011324835
pvsvf_sd       0.0015172431 0.0010548195 0.0011982428 0.0010898782 0.0015700286
cpvf_baseline  0.0003027970 0.0004499471 0.0004553564 0.0003754265 0.0002413853
cpvf_sd        0.0002903707 0.0004132152 0.0004777504 0.0004609862 0.0002313286
                sub-JUSL440  sub-JUSL465  sub-JUSL489  sub-JUSL497  sub-JUSL509
pvsvf_baseline 0.0009988878 0.0004733593 0.0008552989 0.0010193347 0.0008174433
pvsvf_sd       0.0013406836 0.0002599142 0.0004963629 0.0011728962 0.0007283381
cpvf_baseline  0.0004306048 0.0003718143 0.0003456033 0.0002199291 0.0002814643
cpvf_sd        0.0003972546 0.0004747714 0.0003718449 0.0002246944 0.0002753545
                sub-JUSL542  sub-JUSL620  sub-JUSL628  sub-JUSL653  sub-JUSL678
pvsvf_baseline 0.0003452104 0.0020482885 0.0004178265 0.0004232350 0.0007347456
pvsvf_sd       0.0004110231 0.0014844100 0.0002679279 0.0014182534 0.0007639784
cpvf_baseline  0.0002413132 0.0003133795 0.0003364672 0.0003238524 0.0005787261
cpvf_sd        0.0002113701 0.0003211150 0.0003373063 0.0003656414 0.0005747235
                sub-JUSL749 sub-JUSO105006 sub-JUSO105009 sub-JUSO105041
pvsvf_baseline 0.0004976326   0.0005081888   0.0005124854   0.0002873435
pvsvf_sd       0.0004218409   0.0005290129   0.0004455506   0.0002377983
cpvf_baseline  0.0003548299   0.0003459288   0.0003297333   0.0003935318
cpvf_sd        0.0003433626   0.0003412096   0.0003482116   0.0003556669
               sub-JUSO105089 sub-JUSO105139 sub-JUSO105155 sub-JUSO105172
pvsvf_baseline   0.0007362982   0.0004898124   0.0012094465   0.0008549121
pvsvf_sd         0.0006716269   0.0003857158   0.0010318576   0.0008951808
cpvf_baseline    0.0002903989   0.0004559942   0.0003274189   0.0004138559
cpvf_sd          0.0003555765   0.0004285556   0.0003645455   0.0004127141
               sub-JUSO105173 sub-JUSO105212 sub-JUSO105217 sub-JUSO105225
pvsvf_baseline   0.0005076512   0.0011512937   0.0007496937   0.0028225609
pvsvf_sd         0.0003929005   0.0007599952   0.0009861743   0.0016514006
cpvf_baseline    0.0002566331   0.0003088223   0.0001857323   0.0002669929
cpvf_sd          0.0002727647   0.0003077536   0.0001904457   0.0002931437
               sub-JUSO105253 sub-JUSO105288 sub-JUSO105319 sub-JUSO105320
pvsvf_baseline   0.0005900437   0.0006192022   0.0003186854   0.0012878759
pvsvf_sd         0.0003554552   0.0007186163   0.0002071128   0.0010656680
cpvf_baseline    0.0002859978   0.0002704107   0.0002912919   0.0002891201
cpvf_sd          0.0003016947   0.0002868576   0.0002907425   0.0002488360
               sub-JUSO105014 sub-JUSO105030 sub-JUSO105036 sub-JUSO105043
pvsvf_baseline   0.0010272115   0.0006884350   0.0017126873   0.0006001087
pvsvf_sd         0.0010869478   0.0006551275   0.0019374580   0.0006926332
cpvf_baseline    0.0003507708   0.0002789102   0.0003112552   0.0003207852
cpvf_sd          0.0002689290   0.0002810249   0.0002950284   0.0002663735
               sub-JUSO105053 sub-JUSO105081 sub-JUSO105096 sub-JUSO105119
pvsvf_baseline   0.0004894640   0.0008703979   0.0015141413   0.0009946393
pvsvf_sd         0.0004012542   0.0008854431   0.0017122912   0.0011621747
cpvf_baseline    0.0003339685   0.0003675703   0.0003481422   0.0003267639
cpvf_sd          0.0002918141   0.0003128831   0.0003878939   0.0002873130
               sub-JUSO105131 sub-JUSO105137 sub-JUSO105149 sub-JUSO105151
pvsvf_baseline   0.0005642804   0.0009614480   0.0010263678   0.0007456400
pvsvf_sd         0.0007522916   0.0010496505   0.0010935714   0.0008254748
cpvf_baseline    0.0003058148   0.0002857663   0.0003604017   0.0004161704
cpvf_sd          0.0002827165   0.0002874178   0.0002761489   0.0004152150
               sub-JUSO105152 sub-JUSO105195 sub-JUSO105196 sub-JUSO105199
pvsvf_baseline   0.0005093549   0.0006680481   0.0003825756   0.0007203520
pvsvf_sd         0.0004471006   0.0003979807   0.0003157101   0.0008916024
cpvf_baseline    0.0003772718   0.0002714978   0.0003611892   0.0003063029
cpvf_sd          0.0003676133   0.0002622611   0.0003714459   0.0002587708
               sub-JUSO105248 sub-JUSO105263 sub-JUSO105265 sub-JUSO105269
pvsvf_baseline   0.0012023244   0.0003520084   0.0006315855   0.0006180771
pvsvf_sd         0.0009181625   0.0003685543   0.0006073895   0.0005923755
cpvf_baseline    0.0003003663   0.0002374339   0.0003706133   0.0003061528
cpvf_sd          0.0002914461   0.0002330244   0.0004438420   0.0002800376
                sub-MELB302  sub-MELB303  sub-MELB306  sub-MELB309  sub-MELB310
pvsvf_baseline 0.0039506328 0.0004809208 0.0007842255 0.0005940500 0.0004792265
pvsvf_sd       0.0038596461 0.0003229066 0.0004844901 0.0009537338 0.0004801160
cpvf_baseline  0.0005731820 0.0002138351 0.0001906663 0.0004110976 0.0002903779
cpvf_sd        0.0005922172 0.0002272771 0.0002061369 0.0003718463 0.0003278694
                sub-MELB312  sub-MELB314  sub-MELB315  sub-MELB316  sub-MELB318
pvsvf_baseline 0.0012411347 0.0006296991 0.0006737970 0.0005441954 0.0008198893
pvsvf_sd       0.0006289951 0.0006463834 0.0006422649 0.0009249076 0.0003512346
cpvf_baseline  0.0003449675 0.0003943574 0.0003195248 0.0003189015 0.0003628031
cpvf_sd        0.0004420406 0.0003765333 0.0003107327 0.0002201998 0.0003463600
                sub-MELB319  sub-MELB320  sub-MELB321  sub-MELB322  sub-MELB323
pvsvf_baseline 0.0008410724 0.0010730482 0.0009258758 0.0006733141 1.888961e-04
pvsvf_sd       0.0007559101 0.0007487975 0.0013890179 0.0006708833 2.074722e-05
cpvf_baseline  0.0003294251 0.0002351980 0.0002871581 0.0002576896 2.919948e-04
cpvf_sd        0.0003525455 0.0002408768 0.0002816524 0.0002545898 3.046688e-04
                sub-MELB324   sub-MONT02   sub-MONT03   sub-MONT06   sub-MONT10
pvsvf_baseline 0.0004953695 0.0002433218 0.0010820958 0.0007386083 0.0018193444
pvsvf_sd       0.0009690918 0.0001957073 0.0009352097 0.0006303721 0.0018547899
cpvf_baseline  0.0003630457 0.0002493595 0.0004281203 0.0002806960 0.0002196163
cpvf_sd        0.0003294772 0.0002720807 0.0004053005 0.0002728935 0.0001153892
                 sub-MONT12   sub-MONT13   sub-MONT16   sub-MONT17   sub-MONT19
pvsvf_baseline 0.0009237734 0.0002445356 0.0003029279 0.0001739833 0.0008365574
pvsvf_sd       0.0008493668 0.0002909962 0.0002571200 0.0002112210 0.0009628362
cpvf_baseline  0.0002477426 0.0004466843 0.0001594156 0.0003685896 0.0003028135
cpvf_sd        0.0003131353 0.0004901986 0.0002084581 0.0003092643 0.0003690811
                 sub-MONT21   sub-MONT24   sub-MONT25   sub-MONT27   sub-MONT28
pvsvf_baseline 1.488935e-05 0.0001059954 0.0002942687 0.0004132567 0.0024806910
pvsvf_sd       2.427743e-05 0.0001119956 0.0003215536 0.0007475810 0.0022314706
cpvf_baseline  1.873979e-04 0.0001263670 0.0002525954 0.0003620363 0.0002566619
cpvf_sd        2.031023e-04 0.0001695157 0.0001707930 0.0004087424 0.0003821069
                 sub-MONT30   sub-MONT31   sub-MONT32   sub-MONT33 sub-NTNU6006
pvsvf_baseline 0.0002472897 0.0005217116 0.0004012986 0.0003056418 0.0006922005
pvsvf_sd       0.0005259734 0.0009298537 0.0003352124 0.0003038388 0.0008212416
cpvf_baseline  0.0002893237 0.0003854970 0.0003989511 0.0003823786 0.0005541912
cpvf_sd        0.0003109267 0.0003549266 0.0002590040 0.0004075645 0.0003432828
               sub-NTNU6007 sub-NTNU6011 sub-NTNU6012 sub-NTNU6013 sub-NTNU6014
pvsvf_baseline 0.0004096884 0.0009239192 0.0009952185 0.0003829001 0.0002647485
pvsvf_sd       0.0004770259 0.0008127158 0.0008294568 0.0003167811 0.0004864231
cpvf_baseline  0.0002291786 0.0004571156 0.0003065070 0.0003140748 0.0004132740
cpvf_sd        0.0001975530 0.0004107849 0.0003563900 0.0003757954 0.0005049648
               sub-NTNU6015 sub-NTNU6019 sub-NTNU6020 sub-NTNU6021 sub-NTNU6022
pvsvf_baseline 0.0008566196 0.0008734316 0.0012844295 0.0003155625 0.0005780920
pvsvf_sd       0.0009370401 0.0010673510 0.0011133457 0.0003793348 0.0005229035
cpvf_baseline  0.0002674231 0.0003055085 0.0002993201 0.0003904100 0.0002861771
cpvf_sd        0.0003663993 0.0003147207 0.0002984812 0.0003437231 0.0002686774
               sub-NTNU6023 sub-NTNU6024 sub-NTNU6025 sub-NTNU6027 sub-NTNU6028
pvsvf_baseline 0.0001668555 0.0023749875 0.0007774815 0.0004770341 0.0010354358
pvsvf_sd       0.0001719933 0.0022553013 0.0009349052 0.0003282758 0.0010131426
cpvf_baseline  0.0004403870 0.0003501035 0.0003606183 0.0003567240 0.0003026518
cpvf_sd        0.0004186577 0.0003557870 0.0002894328 0.0003261506 0.0003190611
               sub-NTNU6032 sub-NTNU6033 sub-NTNU6034 sub-NTNU6037 sub-NTNU6040
pvsvf_baseline 0.0005108216 0.0017045727 0.0003504161 0.0011141069 2.769479e-05
pvsvf_sd       0.0004940659 0.0015419219 0.0002932576 0.0011280468 2.365903e-04
cpvf_baseline  0.0004190181 0.0002951391 0.0001720108 0.0003409070 3.700675e-04
cpvf_sd        0.0005031950 0.0003442677 0.0002221237 0.0003162477 3.320456e-04
               sub-NTNU6041 sub-NTNU6043 sub-NTNU6047 sub-NTNU6048 sub-NTNU6057
pvsvf_baseline 0.0008820381 0.0006085061 0.0014112942 0.0008276128 0.0006063735
pvsvf_sd       0.0007023802 0.0008673858 0.0011327922 0.0008120119 0.0009352155
cpvf_baseline  0.0003383904 0.0003571100 0.0004498184 0.0004128042 0.0003277262
cpvf_sd        0.0003118977 0.0003450764 0.0004517553 0.0005439768 0.0003972870
               sub-NTNU6059 sub-NTNU6060 sub-NTNU6066 sub-NTNU6068 sub-NTNU6072
pvsvf_baseline 0.0005807844 0.0005074184 0.0008349577 0.0013982450 0.0002653696
pvsvf_sd       0.0006926320 0.0004973515 0.0007637619 0.0013439468 0.0003740820
cpvf_baseline  0.0004635171 0.0003495669 0.0001389002 0.0002657940 0.0003320263
cpvf_sd        0.0004566955 0.0002788092 0.0002321750 0.0002763413 0.0004090731
               sub-NTNU6075 sub-NTNU6078 sub-NTNU6080 sub-NTNU6083 sub-NTNU6087
pvsvf_baseline 0.0003723613 0.0004342823 0.0006211488 0.0001624543 0.0002505804
pvsvf_sd       0.0002789322 0.0004043304 0.0004467602 0.0001132677 0.0001997356
cpvf_baseline  0.0002503546 0.0003762778 0.0002728718 0.0003719636 0.0002382055
cpvf_sd        0.0002257050 0.0004096409 0.0002255163 0.0002975951 0.0002105957
               sub-NTNU6088 sub-NTNU6089 sub-NTNU6091 sub-NTNU6093 sub-NTNU6094
pvsvf_baseline 0.0008913297 0.0005560666 0.0012984112 0.0014977310 0.0006970877
pvsvf_sd       0.0006464713 0.0007067782 0.0013300034 0.0015202375 0.0009082648
cpvf_baseline  0.0002901176 0.0003946905 0.0003453550 0.0002940041 0.0004089966
cpvf_sd        0.0002986233 0.0003198451 0.0003954298 0.0005606127 0.0003004872
               sub-NTNU6096 sub-NTNU6097 sub-NTNU6100 sub-NTNU6101 sub-NTNU6102
pvsvf_baseline 0.0019522936 0.0004274851 0.0002655452 0.0016895959 0.0018654097
pvsvf_sd       0.0017236084 0.0002447330 0.0001417853 0.0016107681 0.0021909495
cpvf_baseline  0.0003273219 0.0002067962 0.0005306538 0.0003121439 0.0002937148
cpvf_sd        0.0002956724 0.0002038991 0.0005560884 0.0003846926 0.0003535787
               sub-NTNU6103 sub-NTNU6104 sub-NTNU6105 sub-NTNU6107 sub-NTNU6109
pvsvf_baseline 0.0001516383 0.0008994907 0.0015230437 0.0004610648 0.0015652500
pvsvf_sd       0.0001763056 0.0003713019 0.0013965147 0.0001331691 0.0017860742
cpvf_baseline  0.0005242170 0.0003312507 0.0002207442 0.0001862003 0.0003304192
cpvf_sd        0.0005148062 0.0002946060 0.0002162717 0.0002153694 0.0003858068
               sub-NTNU6110 sub-NTNU6111 sub-NTNU6112 sub-NTNU6113 sub-NTNU6116
pvsvf_baseline 0.0001591231 0.0009355281 0.0014620396 0.0007378665 0.0011897561
pvsvf_sd       0.0002418760 0.0009609867 0.0015098632 0.0005247337 0.0010117094
cpvf_baseline  0.0003261001 0.0002474387 0.0004360521 0.0003226454 0.0003081422
cpvf_sd        0.0002742293 0.0003124603 0.0002767447 0.0003695810 0.0002183421
               sub-NTNU6117 sub-NTNU6122 sub-NTNU6126 sub-NTNU6128 sub-NTNU6129
pvsvf_baseline 0.0009501067 0.0016793735 0.0001736669 0.0006000995 0.0009929336
pvsvf_sd       0.0010251655 0.0014935131 0.0001934538 0.0005803771 0.0009097041
cpvf_baseline  0.0003701080 0.0003199246 0.0003026313 0.0004499562 0.0004506905
cpvf_sd        0.0002405461 0.0002953148 0.0003009307 0.0004851680 0.0003845275
               sub-NTNU6131 sub-NTNU6132 sub-NTNU6133 sub-NTNU6139 sub-NTNU6146
pvsvf_baseline 0.0006819099 0.0004844944 0.0027505591 0.0015332158 0.0006943190
pvsvf_sd       0.0007119384 0.0006416052 0.0025478446 0.0014124658 0.0006445061
cpvf_baseline  0.0006608377 0.0003436656 0.0003928228 0.0003837090 0.0001752951
cpvf_sd        0.0005013170 0.0002649688 0.0004213343 0.0003102429 0.0002634373
               sub-NTNU6150 sub-NTNU6151 sub-NTNU6152 sub-NTNU6153 sub-NTNU6155
pvsvf_baseline 0.0012824984 0.0006224481 0.0007396099 0.0033659515 0.0015259369
pvsvf_sd       0.0012694853 0.0006485301 0.0003792770 0.0039080333 0.0013043335
cpvf_baseline  0.0001953444 0.0003454566 0.0003092558 0.0002596571 0.0003674970
cpvf_sd        0.0002242662 0.0003166335 0.0002927128 0.0002418777 0.0001505605
               sub-NTNU6157 sub-NTNU6160 sub-OSLO59616 sub-OSLO59617
pvsvf_baseline 0.0009678026 0.0003059540  0.0023015412  0.0004255534
pvsvf_sd       0.0007501197 0.0001782695  0.0021780742  0.0007149501
cpvf_baseline  0.0003183153 0.0002358758  0.0005218607  0.0002449498
cpvf_sd        0.0002965966 0.0002515541  0.0004780519  0.0002645827
               sub-OSLO59618 sub-OSLO59619 sub-OSLO59621 sub-OSLO59623
pvsvf_baseline  0.0013665616  0.0010953439  0.0020385131  0.0021813163
pvsvf_sd        0.0009546081  0.0004956552  0.0017958527  0.0018857079
cpvf_baseline   0.0003596749  0.0002670886  0.0002024278  0.0003796439
cpvf_sd         0.0003547071  0.0002544309  0.0002331911  0.0003791683
               sub-OSLO59624 sub-OSLO59625 sub-OSLO59626 sub-OSLO59627
pvsvf_baseline  0.0008705248  0.0003320530  0.0022512809  0.0007303545
pvsvf_sd        0.0011022538  0.0005987595  0.0014996526  0.0009846276
cpvf_baseline   0.0002801143  0.0002930112  0.0001708218  0.0002311600
cpvf_sd         0.0002688306  0.0002999287  0.0001427373  0.0002497069
               sub-OSLO59628 sub-OSLO59629 sub-OSLO59631 sub-OSLO59632
pvsvf_baseline  0.0010756085  0.0006020225  0.0003288056  0.0003250947
pvsvf_sd        0.0010289647  0.0004130538  0.0004720681  0.0006345417
cpvf_baseline   0.0001954677  0.0005691971  0.0005645067  0.0004196740
cpvf_sd         0.0002070898  0.0006685752  0.0004825338  0.0003772801
               sub-OSLO59633 sub-OSLO59634 sub-OSLO59635 sub-OSLO59636
pvsvf_baseline  0.0013780182  0.0004003745  0.0013975955  0.0004696877
pvsvf_sd        0.0011303753  0.0006756129  0.0004890823  0.0009231226

Run harmonization for the diffusion features:

In [42]:
%%R -i dwi_feat,dwi_subs
rownames(dwi_feat) <- dwi_subs
dwi.harmonized <- neuroCombat(dat=t(dwi_feat), batch=dwi.batch, mod=dwi.mod)
dwi.harmonized

[neuroCombat] Found 8 missing data values.
[neuroCombat] Performing ComBat with empirical Bayes
[neuroCombat] Found 4 batches
[neuroCombat] Adjusting for  6  covariate(s) or covariate level(s)
[neuroCombat] Standardizing Data across features
[neuroCombat] Fitting L/S model and finding priors
[neuroCombat] Finding parametric adjustments
[neuroCombat] Adjusting the Data
$dat.combat
              sub-BRUX001 sub-BRUX003 sub-BRUX004 sub-BRUX006 sub-BRUX007
mfwi_baseline   0.2681668   0.2721712   0.2674623   0.2754461   0.2578421
mfwi_sd         0.2632243   0.2694699   0.2638246   0.2713102   0.2544989
alps_baseline   1.2933176   1.3311018   1.0073735   1.0136124   1.4457154
alps_sd         1.2976259   1.3171068   1.1524802   1.2007242   1.4203252
              sub-BRUX008 sub-BRUX010 sub-BRUX012 sub-BRUX013 sub-BRUX014
mfwi_baseline   0.2762403   0.2863653   0.2702704   0.2663991   0.2890037
mfwi_sd         0.2745684   0.2823656   0.2658014   0.2637082   0.2868012
alps_baseline   1.6426505   1.5123031   1.2963957   1.6529906   1.3799282
alps_sd         1.4929701   1.4712642   1.3123717   1.4985605   1.3616927
              sub-BRUX015 sub-BRUX017 sub-BRUX018 sub-BRUX019 sub-BRUX020
mfwi_baseline   0.2696732   0.2768329   0.2590561   0.2806655   0.2540403
mfwi_sd         0.2660166   0.2768701   0.2593931   0.2788102   0.2521275
alps_baseline   1.0738144   1.3487083   1.2957255   1.5606501   1.7983229
alps_sd         1.2196582   1.3281566   1.3133213   1.4572654   1.5876256
              sub-BRUX021 sub-BRUX022 sub-BRUX023 sub-BRUX024 sub-BRUX025
mfwi_baseline   0.2616037   0.2688196   0.2587321   0.2706112   0.2714519
mfwi_sd         0.2587910   0.2673797   0.2578174   0.2694916   0.2743281
alps_baseline   1.7602877   1.0890123   1.1817601   1.3261670   0.7481596
alps_sd         1.5449650   1.2228327   1.2617828   1.3291047   1.0076327
              sub-BRUX026 sub-BRUX027 sub-BRUX029 sub-BRUX030 sub-BRUX070
mfwi_baseline   0.2609508   0.2624916   0.2576614   0.2633758   0.2825557
mfwi_sd         0.2614341   0.2610594   0.2570810   0.2621481   0.2815149
alps_baseline   0.9950120   0.9233683   1.6581979   1.1137935   1.7676872
alps_sd         1.1426316   1.1036570   1.5000679   1.2278215   1.5512639
              sub-JUSL018 sub-JUSL067 sub-JUSL070 sub-JUSL080 sub-JUSL083
mfwi_baseline   0.2985225   0.2734755   0.3176504   0.2797531   0.2868344
mfwi_sd         0.2952959   0.2738916   0.3005950   0.2776388   0.2837130
alps_baseline   1.4214749   1.4329235   1.4538547   1.3920570   1.3707836
alps_sd         1.3327413   1.4154313         NaN   1.4122306         NaN
              sub-JUSL104 sub-JUSL156 sub-JUSL180 sub-JUSL182 sub-JUSL183
mfwi_baseline   0.2519208   0.2831353   0.2656039   0.2699942   0.2889018
mfwi_sd         0.2515638   0.2829947   0.2648764   0.2622275   0.2881781
alps_baseline   1.4047658   1.4189999   1.8907989   1.5315983   1.3693373
alps_sd         1.4207099   1.3248796   1.4190507   1.3941588         NaN
              sub-JUSL198 sub-JUSL204 sub-JUSL207 sub-JUSL221 sub-JUSL256
mfwi_baseline   0.2605316   0.2757360   0.2566578   0.2765018   0.2679925
mfwi_sd         0.2617378   0.2761821   0.2535819   0.2761845   0.2674892
alps_baseline   1.3920441   1.4642473   1.3950072   1.4033870   1.3956326
alps_sd         1.2127952   1.1961510   1.3201614   1.2706867   0.8453905
              sub-JUSL259 sub-JUSL261 sub-JUSL280 sub-JUSL295 sub-JUSL321
mfwi_baseline   0.2885224   0.2657685   0.2811731   0.2781537   0.2615727
mfwi_sd         0.2846101   0.2669212   0.2840202   0.2770948   0.2576447
alps_baseline   1.3706619   1.4444758   1.3481683   1.3622845   1.4542302
alps_sd         1.3608896   1.4636994   1.4102816   1.3180557   1.4472639
              sub-JUSL322 sub-JUSL326 sub-JUSL332 sub-JUSL353 sub-JUSL354
mfwi_baseline   0.2717555   0.2674217   0.2560442   0.2673804   0.2886448
mfwi_sd         0.2762954   0.2691789   0.2479933   0.2738977   0.2946554
alps_baseline   1.4109299   1.4034114  -0.4439654   1.3677881   1.4393274
alps_sd         1.3342227   1.4025488   1.4233492   1.3061306   1.3892503
              sub-JUSL391 sub-JUSL465 sub-JUSL489 sub-JUSL497 sub-JUSL509
mfwi_baseline   0.2606078   0.2779825   0.2604802   0.2745757   0.2630695
mfwi_sd         0.2638215   0.2766971   0.2560996   0.2717024   0.2610946
alps_baseline   1.3623351   1.3370160   1.3500272   1.4163044   1.3950534
alps_sd         1.3464077   1.4139871   1.3661851   1.3980006   1.3507703
              sub-JUSL542 sub-JUSL620 sub-JUSL628 sub-JUSL653 sub-JUSL678
mfwi_baseline   0.2769843   0.2763552   0.2863465   0.2761738   0.2734377
mfwi_sd         0.2760404   0.2766927   0.2818022   0.2699625   0.2765996
alps_baseline   1.3543905   1.4634774   1.3986025   1.3935730   1.3790051
alps_sd         1.3550426   1.3866183   1.3976535   1.6549210   1.2606803
              sub-JUSL749 sub-NTNU6006 sub-NTNU6007 sub-NTNU6011 sub-NTNU6012
mfwi_baseline   0.2572552    0.2705999    0.2799094    0.2840667    0.2654023
mfwi_sd         0.2608062    0.2577775    0.2806025    0.2740322    0.2630410
alps_baseline   1.3912376    1.1440257    1.5690739    1.4606662    1.2815839
alps_sd               NaN    1.2109638    1.5860670    1.3838255    1.3288933
              sub-NTNU6013 sub-NTNU6014 sub-NTNU6015 sub-NTNU6019 sub-NTNU6020
mfwi_baseline    0.2762554    0.2492341    0.2768326    0.2803926    0.2766365
mfwi_sd          0.2716616    0.2585898    0.2865805    0.2509966    0.2625639
alps_baseline    1.3369240    1.2862912    0.9737091    1.4873312    1.7285454
alps_sd          1.2970935    1.3878391    1.1627773    1.4329403    1.5179856
              sub-NTNU6021 sub-NTNU6022 sub-NTNU6023 sub-NTNU6024 sub-NTNU6025
mfwi_baseline    0.2692357    0.2711060    0.2603113    0.2586283    0.2745383
mfwi_sd          0.2747660    0.2733071    0.2595948    0.2713903    0.2568786
alps_baseline    0.9830612    1.7201990    1.5035075    1.3339314    1.5188261
alps_sd          1.1711640    1.6274897    1.5254932    1.3580869    1.4037908
              sub-NTNU6027 sub-NTNU6028 sub-NTNU6032 sub-NTNU6033 sub-NTNU6034
mfwi_baseline    0.2595835    0.2562662    0.2433326    0.2739803    0.2521965
mfwi_sd          0.2774235    0.2658867    0.2717377    0.2634040    0.2568565
alps_baseline    1.5864004    1.5026196    1.3980362    1.3469663    1.0604437
alps_sd          1.4890747    1.4350139    1.6495419    1.2853228    1.2113880
              sub-NTNU6037 sub-NTNU6040 sub-NTNU6041 sub-NTNU6043 sub-NTNU6047
mfwi_baseline    0.2716589    0.2631904    0.2730852    0.2722240    0.2841014
mfwi_sd          0.2751536    0.2592204    0.2730550    0.2799333    0.2982836
alps_baseline    1.5667446    1.8824868    1.7137889    1.5270990    1.2930087
alps_sd          1.4959115    1.5816138    1.5580155    1.4507887    1.3003188
              sub-NTNU6048 sub-NTNU6057 sub-NTNU6059 sub-NTNU6060 sub-NTNU6066
mfwi_baseline    0.2701966    0.2746142    0.2280597    0.2907568    0.2720053
mfwi_sd          0.2807657    0.2747171    0.2670360    0.2825371    0.2727792
alps_baseline    1.6936151    1.2276562    1.0614763    1.3544830    0.9220153
alps_sd          1.5321809    1.3432014    1.2432968    1.3849961    1.1465578
              sub-NTNU6068 sub-NTNU6072 sub-NTNU6075 sub-NTNU6078 sub-NTNU6080
mfwi_baseline    0.2729555    0.2810496    0.2759333    0.2863054    0.2710701
mfwi_sd          0.2782869    0.2815231    0.2683637    0.2714151    0.2647622
alps_baseline    1.2528071    0.7096062    1.0914544    1.1299952    1.2275016
alps_sd          1.1616874    1.0110584    1.2009029    1.1887633    1.2880444
              sub-NTNU6083 sub-NTNU6087 sub-NTNU6088 sub-NTNU6089 sub-NTNU6091
mfwi_baseline    0.2802259    0.2748458    0.2654142    0.2654372    0.2749193
mfwi_sd          0.2726790    0.2431782    0.2618184    0.2661628    0.2611331
alps_baseline    1.4069694    1.8164880    0.9422887    1.2016682    1.3714054
alps_sd          1.4033612    1.4937014    1.1028540    1.2988150    1.3427910
              sub-NTNU6093 sub-NTNU6094 sub-NTNU6096 sub-NTNU6097 sub-NTNU6100
mfwi_baseline    0.2617060    0.2790654    0.2840392    0.2614392    0.2753346
mfwi_sd          0.2770163    0.2667684    0.2846030    0.2665843    0.2578371
alps_baseline    1.5504976    1.6975042    1.8271741    1.2164585    1.1968844
alps_sd          1.5275268    1.5890571    1.5827078    1.2602252    1.2657317
              sub-NTNU6101 sub-NTNU6102 sub-NTNU6103 sub-NTNU6104 sub-NTNU6105
mfwi_baseline    0.2688992    0.2699193    0.2542081    0.2706706    0.2737276
mfwi_sd          0.2699684    0.2640950    0.2583571    0.2851593    0.2766491
alps_baseline    2.0756935    1.4669114    1.4947374    1.2288110    1.1781286
alps_sd          1.6936053    1.4047076    1.4855072    1.3676788    1.2856829
              sub-NTNU6107 sub-NTNU6109 sub-NTNU6110 sub-NTNU6111 sub-NTNU6112
mfwi_baseline    0.2661997    0.2889203    0.2789590    0.2576604    0.2845335
mfwi_sd          0.2618408    0.2984507    0.2739821    0.2698351    0.2626145
alps_baseline    1.3794434    1.1941348    1.0682742    1.4693679    1.2226025
alps_sd          1.3273318    1.2740129    1.1118529    1.4577189    1.2894338
              sub-NTNU6113 sub-NTNU6116 sub-NTNU6117 sub-NTNU6122 sub-NTNU6126
mfwi_baseline    0.2799875    0.2681908    0.2905504    0.2766345    0.2643798
mfwi_sd          0.2782171    0.2710191    0.2853044    0.2728125    0.2622150
alps_baseline    1.4380373    1.2586865    0.8628136    0.9242364    0.9811702
alps_sd          1.4019413    1.3122990    1.0932909    1.1155820    1.1246730
              sub-NTNU6128 sub-NTNU6129 sub-NTNU6131 sub-NTNU6132 sub-NTNU6133
mfwi_baseline    0.2672250    0.2685144    0.2682976    0.2722736    0.2789841
mfwi_sd          0.2655621    0.2725864    0.2618111    0.2852477    0.2794101
alps_baseline    1.4987164    1.2744669    1.0839914    1.4442766    1.7656936
alps_sd          1.5026872    1.3036313    1.2465319    1.3975536    1.5507036
              sub-NTNU6139 sub-NTNU6146 sub-NTNU6150 sub-NTNU6151 sub-NTNU6152
mfwi_baseline    0.2644213    0.2929555    0.2774719    0.3050051    0.2625403
mfwi_sd          0.2613309    0.2898432    0.2671490    0.2681696    0.2471515
alps_baseline    1.1368584    1.4113126    0.9208346    1.2102511    0.9751101
alps_sd          1.2867007    1.4424995    1.1072044    1.2898903    1.1267421
              sub-NTNU6153 sub-NTNU6155 sub-NTNU6157 sub-NTNU6160 sub-OSLO59616
mfwi_baseline    0.2914246    0.2921323    0.2716110    0.2651045     0.2821272
mfwi_sd          0.2783168    0.2790548    0.2548962    0.2571546     0.2865136
alps_baseline    1.2492545    1.2049782    1.1470033    1.2373705     1.2611112
alps_sd          1.3219905    1.1765883    1.1558104    1.3330438     1.3024136
              sub-OSLO59617 sub-OSLO59618 sub-OSLO59619 sub-OSLO59621
mfwi_baseline           NaN     0.2661583     0.2887680     0.2786391
mfwi_sd                 NaN     0.2668581     0.2860272     0.2738564
alps_baseline      1.043359     1.6126872     1.5118291     0.9148640
alps_sd            1.222755     1.5028567     1.4067959     1.1041200
              sub-OSLO59623 sub-OSLO59624 sub-OSLO59625 sub-OSLO59626
mfwi_baseline     0.2717391     0.2799046     0.2685963     0.2809274
mfwi_sd           0.2704313     0.2721995     0.2659912     0.2723419
alps_baseline     1.2421676     1.7099112     1.2220795     1.5960867
alps_sd           1.2944582     1.5592331     1.2711908     1.5433113
              sub-OSLO59627 sub-OSLO59628 sub-OSLO59629 sub-OSLO59631
mfwi_baseline     0.2552729     0.2801596     0.2858761           NaN
mfwi_sd           0.2523819     0.2776586     0.2845691           NaN
alps_baseline     1.5344989     0.7649331     1.2009774       1.28257
alps_sd           1.5177694     1.0205085     1.2835728       1.29130
              sub-OSLO59632 sub-OSLO59633 sub-OSLO59634 sub-OSLO59635
mfwi_baseline     0.2626319     0.2686743     0.2848541     0.2680538
mfwi_sd           0.2633590     0.2676021     0.2850371     0.2696343
alps_baseline     0.9850957     1.5209954     1.5015153     1.3492655
alps_sd           1.1794452     1.5113901     1.4609694     1.3962770
              sub-OSLO59636 sub-OSLO59637 sub-OSLO59638 sub-OSLO59639
mfwi_baseline     0.2590497     0.2741697     0.2671087     0.2705153
mfwi_sd           0.2607821     0.2771202     0.2719623     0.2636575
alps_baseline     1.4924974     0.8825965     1.2911857     1.3893400
alps_sd           1.4238471     1.0796781     1.2741857     1.4007699
              sub-OSLO59640 sub-OSLO59641 sub-OSLO59642 sub-OSLO59643
mfwi_baseline     0.2605641     0.2712611     0.2792168     0.2743642
mfwi_sd           0.2692844     0.2687835     0.2838233     0.2696939
alps_baseline     1.3955685     1.3458506     1.3623432     1.4788251
alps_sd           1.4012512     1.3499224     1.3421099     1.4093965
              sub-OSLO59644 sub-OSLO59645 sub-OSLO59646 sub-OSLO59647
mfwi_baseline     0.2536155     0.2707816     0.2752301     0.2696545
mfwi_sd           0.2670390     0.2365609     0.2698394     0.2677266
alps_baseline     1.6451117     0.9390941     1.2433197     1.3590772
alps_sd           1.4598134     1.1986779     1.2901065     1.3771970
              sub-OSLO59650 sub-OSLO59651 sub-OSLO59653 sub-OSLO59654
mfwi_baseline     0.2727983     0.2634421     0.2765743     0.2763795
mfwi_sd           0.2674862     0.2644857     0.2751686     0.2732733
alps_baseline     0.9348078     1.4251138     0.9627893     1.4197158
alps_sd           1.0659020     1.3763760     1.1554924     1.3967854
              sub-OSLO59655 sub-OSLO59656 sub-OSLO59657
mfwi_baseline     0.2815866     0.2555198     0.2546935
mfwi_sd           0.2762276     0.2574265     0.2584631
alps_baseline     1.3063145     1.4981420     1.5725459
alps_sd           1.3397322     1.4433432     1.4908175

$estimates
$estimates$gamma.hat
  mfwi_baseline   mfwi_sd alps_baseline    alps_sd
1     -5.288468 -5.388878    -0.2220132 -0.5305945
2      4.485325  4.766430    -1.4425738 -2.5601619
3     -1.658336 -1.771676     0.5161155  0.9503064
4      2.549959  2.568412     0.5501821  1.0016201

$estimates$delta.hat
  mfwi_baseline   mfwi_sd alps_baseline   alps_sd
1     0.2210188 0.2227004     0.3133494 1.3457953
2     1.8359906 1.7297497     3.8926281 0.4821438
3     1.0574998 1.0638133     0.2637713 1.1641227
4     0.6756331 0.7733149     0.2070314 0.9982178

$estimates$gamma.star
  mfwi_baseline   mfwi_sd alps_baseline    alps_sd
1     -5.285470 -5.385739    -0.2262453 -0.5439839
2      4.474606  4.755330    -1.4245187 -2.5544288
3     -1.650340 -1.762858     0.5137971  0.9395596
4      2.534628  2.551047     0.5586671  1.0165654

$estimates$delta.star
  mfwi_baseline   mfwi_sd alps_baseline   alps_sd
1     0.2539126 0.2553128     0.3307615 1.1901440
2     1.8134786 1.7248475     3.5295415 0.7051336
3     1.0226968 1.0281212     0.3422137 1.1141452
4     0.6577055 0.7311138     0.3013789 0.9042381

$estimates$gamma.bar
         1          2          3          4
-2.8574884  1.3122547 -0.4908975  1.6675432

$estimates$t2
        1         2         3         4
 8.225920 14.861463  2.031483  1.094057

$estimates$a.prior
       1        2        3        4
2.918921 3.975312 6.494227 5.971344

$estimates$b.prior
       1        2        3        4
1.008808 5.906376 4.875037 3.298732

$estimates$stand.mean
              sub-BRUX001 sub-BRUX003 sub-BRUX004 sub-BRUX006 sub-BRUX007
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-BRUX008 sub-BRUX010 sub-BRUX012 sub-BRUX013 sub-BRUX014
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-BRUX015 sub-BRUX017 sub-BRUX018 sub-BRUX019 sub-BRUX020
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-BRUX021 sub-BRUX022 sub-BRUX023 sub-BRUX024 sub-BRUX025
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-BRUX026 sub-BRUX027 sub-BRUX029 sub-BRUX030 sub-BRUX070
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL018 sub-JUSL067 sub-JUSL070 sub-JUSL080 sub-JUSL083
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL104 sub-JUSL156 sub-JUSL180 sub-JUSL182 sub-JUSL183
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL198 sub-JUSL204 sub-JUSL207 sub-JUSL221 sub-JUSL256
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL259 sub-JUSL261 sub-JUSL280 sub-JUSL295 sub-JUSL321
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL322 sub-JUSL326 sub-JUSL332 sub-JUSL353 sub-JUSL354
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL391 sub-JUSL465 sub-JUSL489 sub-JUSL497 sub-JUSL509
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL542 sub-JUSL620 sub-JUSL628 sub-JUSL653 sub-JUSL678
mfwi_baseline   0.2626098   0.2626098   0.2626098   0.2626098   0.2626098
mfwi_sd         0.2633385   0.2633385   0.2633385   0.2633385   0.2633385
alps_baseline   1.4212802   1.4212802   1.4212802   1.4212802   1.4212802
alps_sd         1.3308676   1.3308676   1.3308676   1.3308676   1.3308676
              sub-JUSL749 sub-NTNU6006 sub-NTNU6007 sub-NTNU6011 sub-NTNU6012
mfwi_baseline   0.2626098    0.2626098    0.2626098    0.2626098    0.2626098

### 3. Output
Enter the adjusted values back into the original dataframe:

In [43]:
%%R -i df -o df
# Initialize counter for changes
num_changes <- 0

for (sub in colnames(anat.adj)) { # Loop over the subjects...
  for (var in rownames(anat.adj)) { # ... and each of the anatomical features
    original_value <- df[df$participant_id == sub, var]
    adjusted_value <- anat.adj[var, sub]
    
    # Replace original values with adjusted values only if different
    if (!isTRUE(all.equal(original_value, adjusted_value))) {
      df[df$participant_id == sub, var] <- adjusted_value # Replace
      num_changes <- num_changes + 1
    }
  }
  
  if (sub %in% colnames(dwi.adj)) { # If this subject has dwi data
    for (var in rownames(dwi.adj)) { # Also loop over the diffusion features
      original_value <- df[df$participant_id == sub, var]
      adjusted_value <- dwi.adj[var, sub]
      
      # And replace those values only if different
      if (!isTRUE(all.equal(original_value, adjusted_value))) {
        df[df$participant_id == sub, var] <- adjusted_value
        num_changes <- num_changes + 1
      }
    }
  }
}

cat("Total values changed after harmonization:", num_changes, "\n")

Total values changed after harmonization: 2404

Remove number index:

In [44]:
df.set_index("participant_id", inplace=True)
df

,site,group,age,sex,kss_score_baseline,kss_score_sd,chronotype,pvsvf_baseline,pvsvf_sd,cpvf_baseline,...,cpvf_sd,mfwi_sd,rfwi_sd,alps_sd,dataset,protocol,sex_male,chrono_morning,chrono_evening,total_deprivation
participant_id,,,,,,,,,,,,,,,,,,,,,
sub-BRUX001,Bruxelles,4.0,19.000000,F,5.000000,7.000000,1.0,0.000555,0.000745,0.000428,...,0.000397,0.263224,0.991811,1.297626,bruxelles-bids,SD,False,True,False,True
sub-BRUX003,Bruxelles,4.0,21.000000,F,3.000000,9.000000,1.0,0.001726,0.001670,0.000302,...,0.000296,0.269470,0.991699,1.317107,bruxelles-bids,SD,False,True,False,True
sub-BRUX004,Bruxelles,4.0,19.000000,F,1.000000,6.000000,3.0,0.000755,0.000962,0.000270,...,0.000223,0.263825,0.988203,1.152480,bruxelles-bids,SD,False,False,False,True
sub-BRUX006,Bruxelles,4.0,29.000000,F,2.000000,5.000000,3.0,0.000120,0.000074,0.000237,...,0.000282,0.271310,0.989983,1.200724,bruxelles-bids,SD,False,False,False,True
sub-BRUX007,Bruxelles,4.0,20.000000,F,1.000000,6.000000,3.0,0.000398,0.000338,0.000248,...,0.000259,0.254499,0.989475,1.420325,bruxelles-bids,SD,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sub-ZURI137,Zurich,4.0,23.052704,M,4.142857,7.571429,3.0,0.000731,0.000341,0.000362,...,0.000334,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
sub-ZURI138,Zurich,4.0,26.762491,M,2.857143,4.142857,1.0,0.000510,0.000438,0.000263,...,0.000291,NaN,NaN,NaN,zurich-bids,SD,True,True,False,True
sub-ZURI140,Zurich,4.0,25.752225,M,3.285714,6.285714,3.0,0.001006,0.000925,0.000349,...,0.000367,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
sub-ZURI141,Zurich,4.0,21.815195,M,2.857143,4.666667,3.0,0.000410,0.000325,0.000320,...,0.000304,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True
sub-ZURI142,Zurich,4.0,25.930185,M,3.142857,5.714286,3.0,0.000586,0.000566,0.000214,...,0.000227,NaN,NaN,NaN,zurich-bids,SD,True,False,False,True

Save to file:

In [45]:
df.to_csv("outputs/harmonized_dataframe.csv")