In [1]:
import os
import numpy as np
import pandas as pd

In [8]:
root = os.getcwd().replace("/code","")
harm = pd.read_csv(f"{root}/all_participants_harmonized.csv").iloc[:,1:]
harm

,participant_id,age,sex,group,kss_score_baseline,kss_score_sd,chronotype,pvsvf-baseline,pvsvf-sleep-deprivation,cpvf-baseline,cpvf-sleep-deprivation,rfwi-baseline,rfwi-sleep-deprivation,dti-alps-baseline,dti-alps-sleep-deprivation
0,sub-JU105006,26.063014,M,4,3.0,8.0,0,0.000336,0.000328,0.000362,0.000313,NaN,NaN,NaN,NaN
1,sub-JU105009,22.808219,F,4,3.0,5.0,0,0.000282,0.000274,0.000306,0.000331,NaN,NaN,NaN,NaN
2,sub-JU105041,21.019178,F,4,2.0,3.0,0,0.000276,0.000330,0.000397,0.000402,NaN,NaN,NaN,NaN
3,sub-JU105089,26.594521,M,4,5.0,7.0,0,0.000413,0.000414,0.000271,0.000296,NaN,NaN,NaN,NaN
4,sub-JU105139,36.350685,F,4,3.0,8.0,0,0.000061,0.000053,0.000403,0.000433,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,sub-ME320,22.000000,M,3,2.5,3.5,2,0.000704,0.000500,0.000207,0.000208,NaN,NaN,NaN,NaN
255,sub-ME321,29.000000,F,3,3.0,8.0,1,0.000322,0.000734,0.000242,0.000248,NaN,NaN,NaN,NaN
256,sub-ME322,23.000000,M,3,2.0,4.0,1,0.000336,0.000632,0.000243,0.000284,NaN,NaN,NaN,NaN
257,sub-ME323,21.000000,M,3,2.0,5.0,0,0.000282,0.000385,0.000270,0.000269,NaN,NaN,NaN,NaN
258,sub-ME324,21.000000,F,3,3.0,3.0,0,0.000111,0.000199,0.000296,0.000314,NaN,NaN,NaN,NaN

In [10]:
df = harm.loc[harm.index.repeat(2)].reset_index(drop=True) # Duplicate rows
df['SD'] = [0,1] * (int(len(df)/2)) # Add SD condition

# KSS
df['KSS'] = df['kss_score_baseline'] # Init KSS column
df.loc[df.SD == 1, "KSS"] = np.nan # Set SD connection as NaN
df['KSS'].fillna(df['kss_score_sd'], inplace=True)

# PVSVF
df['PVSVF'] = df["pvsvf-baseline"] # Init PVSVF column
df.loc[df.SD == 1, "PVSVF"] = np.nan # Set SD connection as NaN
df['PVSVF'].fillna(df["pvsvf-sleep-deprivation"], inplace=True)

# CPVF
df['CPVF'] = df["cpvf-baseline"] # Init CPVF column
df.loc[df.SD == 1, "CPVF"] = np.nan # Set SD connection as NaN
df['CPVF'].fillna(df["cpvf-sleep-deprivation"], inplace=True)

# RFWI
col_a = "rfwi-baseline"
col_b = "rfwi-sleep-deprivation"
df.loc[(df[col_a].isna()) ^ (df[col_b].isna()), [col_a, col_b]] = np.nan
df['RFWI'] = df[col_a] # Init RWFI column
df.loc[df.SD == 1, "RFWI"] = np.nan # Set SD connection as NaN
df['RFWI'].fillna(df[col_b], inplace=True)

# DTI-ALPS
col_a = "dti-alps-baseline"
col_b = "dti-alps-sleep-deprivation"
df.loc[(df[col_a].isna()) ^ (df[col_b].isna()), [col_a, col_b]] = np.nan
df['ALPS'] = df[col_a] # Init ALPS column
df.loc[df.SD == 1, "ALPS"] = np.nan # Set SD connection as NaN
df['ALPS'].fillna(df[col_b], inplace=True)
df

,participant_id,age,sex,group,kss_score_baseline,kss_score_sd,chronotype,pvsvf-baseline,pvsvf-sleep-deprivation,cpvf-baseline,...,rfwi-baseline,rfwi-sleep-deprivation,dti-alps-baseline,dti-alps-sleep-deprivation,SD,KSS,PVSVF,CPVF,RFWI,ALPS
0,sub-JU105006,26.063014,M,4,3.0,8.0,0,0.000336,0.000328,0.000362,...,NaN,NaN,NaN,NaN,0,3.0,0.000336,0.000362,NaN,NaN
1,sub-JU105006,26.063014,M,4,3.0,8.0,0,0.000336,0.000328,0.000362,...,NaN,NaN,NaN,NaN,1,8.0,0.000328,0.000313,NaN,NaN
2,sub-JU105009,22.808219,F,4,3.0,5.0,0,0.000282,0.000274,0.000306,...,NaN,NaN,NaN,NaN,0,3.0,0.000282,0.000306,NaN,NaN
3,sub-JU105009,22.808219,F,4,3.0,5.0,0,0.000282,0.000274,0.000306,...,NaN,NaN,NaN,NaN,1,5.0,0.000274,0.000331,NaN,NaN
4,sub-JU105041,21.019178,F,4,2.0,3.0,0,0.000276,0.000330,0.000397,...,NaN,NaN,NaN,NaN,0,2.0,0.000276,0.000397,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,sub-ME322,23.000000,M,3,2.0,4.0,1,0.000336,0.000632,0.000243,...,NaN,NaN,NaN,NaN,1,4.0,0.000632,0.000284,NaN,NaN
514,sub-ME323,21.000000,M,3,2.0,5.0,0,0.000282,0.000385,0.000270,...,NaN,NaN,NaN,NaN,0,2.0,0.000282,0.000270,NaN,NaN
515,sub-ME323,21.000000,M,3,2.0,5.0,0,0.000282,0.000385,0.000270,...,NaN,NaN,NaN,NaN,1,5.0,0.000385,0.000269,NaN,NaN
516,sub-ME324,21.000000,F,3,3.0,3.0,0,0.000111,0.000199,0.000296,...,NaN,NaN,NaN,NaN,0,3.0,0.000111,0.000296,NaN,NaN
517,sub-ME324,21.000000,F,3,3.0,3.0,0,0.000111,0.000199,0.000296,...,NaN,NaN,NaN,NaN,1,3.0,0.000199,0.000314,NaN,NaN

In [13]:
out = pd.DataFrame({"SUB" : df["participant_id"],
                    "GROUP" : df["group"],
                     "SD" : df["SD"],
                     "AGE" : df["age"],
                     "SEX" : df["sex"],
                     "KSS" : df["KSS"],
                     "CHRONO" : df["chronotype"],
                     "PVSVF" : df["PVSVF"],
                     "CPVF" : df["CPVF"],
                     "RFWI" : df["RFWI"],
                     "ALPS" : df["ALPS"]})
out.set_index("SUB", inplace=True)
out.to_csv(f"{root}/all_participants_dataframe.csv")